version: '3.8'

services:
  pernambuco_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      # Espelha o código local para dentro do container
      - .:/app
      # Evita usar a node_modules da máquina host
      - /app/node_modules
    environment:
      # Faz o hot-reload do Vite funcionar dentro do Docker
      - CHOKIDAR_USEPOLLING=true
